### PR TITLE
Workaround for a V8 bug exposed by EventEmitter

### PR DESCRIPTION
**Pull request by ronkorving**
This PR currently only adds a test, and it fails on Node > 0.10. I added more Node targets in the travis config to ensure we get full data. Issue first identified in #44

### CODE REVIEW

**Comment by ronkorving** [comment]
Current thoughts:

We don't properly instantiate Tomes as event emitters. We call inherits() but not the EventEmitter constructor. We can't assume that will always work I think. Adding `EventEmitter.call(this);` in our constructor only inflates our issues though. We end up with a `domains` property, which we cannot suppress because of code in Node [like this](https://github.com/nodejs/node/blob/c6656db352973d6aea24cb1a3c76adf042b25446/lib/events.js#L37). That overwrites whatever behaviors we decided `domain` should have. Very annoying.

Where we put `EventEmitter.call(this)`, at the start of our constructor or at the end doesn't change much. We end up with properties all over the place when we JSON stringify.

I first thought, lets stop this nonsense of blacklisting properties and fix things at the ObjectTome, where we could add a toJSON method to control how objects are serialized (every Tome type, except Object, already does this). But the problem I foresee with that is that we may break `Object.keys(myObjectTome)`, which I'm sure we care about a lot. If we're lucky though, valueOf could be use `valueOf` internally, but [this seems unlikely](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/keys). Continuing my investigation...

**Comment by ronkorving** [comment]
I've found the edge case and smallest test case:

```js
function Obj() {
  Object.defineProperties(this, { foo: { configurable: true, writable: true, value: true } });
}

Obj.prototype.foo = undefined;

var o = new Obj();

console.log(JSON.stringify(o));
console.log(JSON.stringify(o, null, '\t'));
```

The output will contain the `foo` property *only* in the beautified JSON.

**Comment by ronkorving** [comment]
I have filed a bug report to the V8 project: https://bugs.chromium.org/p/v8/issues/detail?id=4903

**Comment by AlmirKadric** [comment]
LGTM 👍

**Comment by ronkorving** [comment]
Added one last test to prove this works for deeply nested objects too.

**Pull request merged**
